//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AliquotaMunicipal
    {
        public string ServicoPmsp { get; set; }
        public string Municipio { get; set; }
        public string UF { get; set; }
        public decimal Aliquota { get; set; }
        public string MunicipioIBGE { get; set; }
    
        public virtual FatServicosPmsp FatServicosPmsp { get; set; }
    }
}
