//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ambiente()
        {
            this.ContratoAmbiente = new HashSet<ContratoAmbiente>();
            this.OrdemServico = new HashSet<OrdemServico>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Andar { get; set; }
        public Nullable<int> TorreBloco { get; set; }
        public Nullable<int> AmbDescricao { get; set; }
    
        public virtual AmbienteAndar AmbienteAndar { get; set; }
        public virtual AmbienteDescricao AmbienteDescricao { get; set; }
        public virtual AmbienteTipo AmbienteTipo { get; set; }
        public virtual AmbienteTorreBloco AmbienteTorreBloco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAmbiente> ContratoAmbiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
    }
}
