//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArquivoProcessamento
    {
        public int Id { get; set; }
        public int DocumentoFiscal { get; set; }
        public System.DateTime Data { get; set; }
        public string RPSSerie { get; set; }
        public Nullable<long> RPSNumero { get; set; }
        public string Xml { get; set; }
        public byte[] Pdf { get; set; }
        public string Url { get; set; }
        public string Mensagens { get; set; }
    
        public virtual DocumentoFiscal DocumentoFiscal1 { get; set; }
    }
}
