//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaixinhaLancadaAprovacao
    {
        public int CaixinhaLancada { get; set; }
        public int Pessoa { get; set; }
        public System.DateTime DataAprovacao { get; set; }
    
        public virtual CaixinhaLancada CaixinhaLancada1 { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
    }
}
