//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caixinha
    {
        public int Id { get; set; }
        public int Beneficario { get; set; }
        public int ContaBancaria { get; set; }
        public System.DateTime DataEntrega { get; set; }
        public decimal Valor { get; set; }
        public string ComprovanteURL { get; set; }
        public string ComprovanteNome { get; set; }
    
        public virtual EmpresaContaBancaria EmpresaContaBancaria { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
