//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChecklistPendencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChecklistPendencia()
        {
            this.OrcamentoMaterial = new HashSet<OrcamentoMaterial>();
        }
    
        public int Id { get; set; }
        public int Checklist { get; set; }
        public string Descricao { get; set; }
        public bool Concluido { get; set; }
        public string Observacao { get; set; }
        public Nullable<int> Album { get; set; }
        public Nullable<int> Acao { get; set; }
        public string Justificativa { get; set; }
        public Nullable<int> VerificadoPor { get; set; }
        public Nullable<System.DateTime> VerificadoEm { get; set; }
        public Nullable<bool> Material { get; set; }
        public string ObsMaterial { get; set; }
        public Nullable<int> QtdMaterial { get; set; }
        public string JustificativaMaterial { get; set; }
    
        public virtual OrdemServicoChecklist OrdemServicoChecklist { get; set; }
        public virtual OrdemServicoChecklistAlbum OrdemServicoChecklistAlbum { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoMaterial> OrcamentoMaterial { get; set; }
    }
}
