//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoAmbiente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratoAmbiente()
        {
            this.ContratoAmbienteAlbum = new HashSet<ContratoAmbienteAlbum>();
            this.ContratoAmbienteEquipamento = new HashSet<ContratoAmbienteEquipamento>();
            this.ContratoDocumento = new HashSet<ContratoDocumento>();
        }
    
        public int Id { get; set; }
        public int Contrato { get; set; }
        public string Nome { get; set; }
        public int Ambiente { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> Andar { get; set; }
        public Nullable<int> TorreBloco { get; set; }
        public string Visitas { get; set; }
        public bool Liberado { get; set; }
        public Nullable<int> Ordem { get; set; }
        public Nullable<int> Criticidade { get; set; }
        public Nullable<int> TipoContrato { get; set; }
        public string Tag { get; set; }
    
        public virtual Ambiente Ambiente1 { get; set; }
        public virtual AmbienteAndar AmbienteAndar { get; set; }
        public virtual AmbienteTipo AmbienteTipo { get; set; }
        public virtual AmbienteTorreBloco AmbienteTorreBloco { get; set; }
        public virtual Contrato Contrato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAmbienteAlbum> ContratoAmbienteAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAmbienteEquipamento> ContratoAmbienteEquipamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoDocumento> ContratoDocumento { get; set; }
    }
}
