//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratoDocumento()
        {
            this.ContratoDocumentoBlob = new HashSet<ContratoDocumentoBlob>();
        }
    
        public int Id { get; set; }
        public int Contrato { get; set; }
        public int TipoDocumento { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<int> Ambiente { get; set; }
        public Nullable<int> Equipamento { get; set; }
    
        public virtual Contrato Contrato1 { get; set; }
        public virtual ContratoAmbiente ContratoAmbiente { get; set; }
        public virtual ContratoAmbienteEquipamento ContratoAmbienteEquipamento { get; set; }
        public virtual TipoDocumento TipoDocumento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoDocumentoBlob> ContratoDocumentoBlob { get; set; }
    }
}
