//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.ContratoTerceiro = new HashSet<ContratoTerceiro>();
            this.OrdemServico = new HashSet<OrdemServico>();
            this.Contrato1 = new HashSet<Contrato>();
            this.Contrato11 = new HashSet<Contrato>();
            this.ContratoAmbiente = new HashSet<ContratoAmbiente>();
            this.ContratoDocumento = new HashSet<ContratoDocumento>();
            this.ContratoEquipeEspecialidade = new HashSet<ContratoEquipeEspecialidade>();
            this.ContratoTerceiroEspecialidade = new HashSet<ContratoTerceiroEspecialidade>();
            this.AmbienteTipo = new HashSet<AmbienteTipo>();
            this.EquipamentoGrupo = new HashSet<EquipamentoGrupo>();
            this.EquipamentoSubTipo = new HashSet<EquipamentoSubTipo>();
            this.EquipamentoTipo = new HashSet<EquipamentoTipo>();
            this.Pessoa5 = new HashSet<Pessoa>();
            this.EspecialidadePreventiva = new HashSet<EspecialidadePreventiva>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int Cliente { get; set; }
        public decimal ValorMensal { get; set; }
        public int Projeto { get; set; }
        public System.DateTime DataInicial { get; set; }
        public System.DateTime DataFinal { get; set; }
        public string Visitas { get; set; }
        public Nullable<bool> Volante { get; set; }
        public Nullable<int> Superior { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<int> Gestor { get; set; }
        public Nullable<int> Vendedor { get; set; }
        public Nullable<int> Gerente { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public Nullable<int> HelpDesk { get; set; }
        public Nullable<int> FaixaVenda { get; set; }
        public bool Ativo { get; set; }
        public Nullable<int> TipoEquipe { get; set; }
        public Nullable<int> Referencia { get; set; }
        public Nullable<int> PeriodicidadeGerente { get; set; }
        public Nullable<int> PeriodicidadeSupervisor { get; set; }
        public string AprovadoEmail { get; set; }
        public string AprovadoDocumento { get; set; }
        public string OrdemCompra { get; set; }
        public string OrdemCompraDocumento { get; set; }
        public string DescritivoNF { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Projeto Projeto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoTerceiro> ContratoTerceiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato1 { get; set; }
        public virtual Contrato Contrato2 { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        public virtual Pessoa Pessoa2 { get; set; }
        public virtual PessoaContato PessoaContato { get; set; }
        public virtual PessoaContato PessoaContato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato11 { get; set; }
        public virtual Contrato Contrato3 { get; set; }
        public virtual Pessoa Pessoa3 { get; set; }
        public virtual Pessoa Pessoa4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAmbiente> ContratoAmbiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoDocumento> ContratoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoEquipeEspecialidade> ContratoEquipeEspecialidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoTerceiroEspecialidade> ContratoTerceiroEspecialidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmbienteTipo> AmbienteTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipamentoGrupo> EquipamentoGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipamentoSubTipo> EquipamentoSubTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipamentoTipo> EquipamentoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialidadePreventiva> EspecialidadePreventiva { get; set; }
    }
}
