//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoAmbienteAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratoAmbienteAlbum()
        {
            this.ContratoAmbienteImagem = new HashSet<ContratoAmbienteImagem>();
        }
    
        public int Id { get; set; }
        public int Ambiente { get; set; }
        public string Descricao { get; set; }
        public string Conclusao { get; set; }
    
        public virtual ContratoAmbiente ContratoAmbiente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAmbienteImagem> ContratoAmbienteImagem { get; set; }
    }
}
