//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContasPagar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContasPagar()
        {
            this.ContasPagarRateio = new HashSet<ContasPagarRateio>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrdemServico { get; set; }
        public string Descricao { get; set; }
        public int Beneficiario { get; set; }
        public int Categoria { get; set; }
        public System.DateTime DataVencimento { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual PagamentoCategoria PagamentoCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContasPagarRateio> ContasPagarRateio { get; set; }
        public virtual OrdemServico OrdemServico1 { get; set; }
    }
}
