//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoAmbienteEquipamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContratoAmbienteEquipamento()
        {
            this.ContratoAmbienteEquipamentoAlbum = new HashSet<ContratoAmbienteEquipamentoAlbum>();
            this.ContratoDocumento = new HashSet<ContratoDocumento>();
        }
    
        public int Id { get; set; }
        public int Ambiente { get; set; }
        public int Equipamento { get; set; }
        public Nullable<System.DateTime> DataValidade { get; set; }
        public string Visitas { get; set; }
        public string Tag { get; set; }
        public bool Liberado { get; set; }
        public Nullable<int> Ordem { get; set; }
        public Nullable<int> Criticidade { get; set; }
        public Nullable<int> TipoContrato { get; set; }
        public string Serial { get; set; }
        public string Patrimonio { get; set; }
        public string DescricaoComplementar { get; set; }
    
        public virtual ContratoAmbiente ContratoAmbiente { get; set; }
        public virtual Equipamento Equipamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAmbienteEquipamentoAlbum> ContratoAmbienteEquipamentoAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoDocumento> ContratoDocumento { get; set; }
    }
}
