//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlePonto
    {
        public int Id { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }
        public decimal Accuracy { get; set; }
        public int Pessoa { get; set; }
    
        public virtual Pessoa Pessoa1 { get; set; }
    }
}
