//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContasPagarRateio
    {
        public int ContasPagar { get; set; }
        public int Projeto { get; set; }
        public decimal Valor { get; set; }
    
        public virtual ContasPagar ContasPagar1 { get; set; }
        public virtual Projeto Projeto1 { get; set; }
    }
}
