//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContaBancaria
    {
        public int Id { get; set; }
        public int Favorecido { get; set; }
        public int Banco { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public decimal SaldoInicial { get; set; }
        public Nullable<bool> TipoConta { get; set; }
    
        public virtual Banco Banco1 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
