//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaContaBancaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpresaContaBancaria()
        {
            this.Caixinha = new HashSet<Caixinha>();
            this.DocumentoFiscal = new HashSet<DocumentoFiscal>();
            this.Pagamento = new HashSet<Pagamento>();
            this.Pessoa = new HashSet<Pessoa>();
            this.Recebimento = new HashSet<Recebimento>();
            this.TransferenciaBancaria = new HashSet<TransferenciaBancaria>();
            this.TransferenciaBancaria1 = new HashSet<TransferenciaBancaria>();
        }
    
        public int Id { get; set; }
        public int Empresa { get; set; }
        public int Banco { get; set; }
        public string Agencia { get; set; }
        public string AgenciaDV { get; set; }
        public string Conta { get; set; }
        public string ContaDV { get; set; }
        public int Carteira { get; set; }
        public decimal SaldoInicial { get; set; }
        public System.DateTime DataSaldo { get; set; }
        public Nullable<decimal> Multa { get; set; }
        public Nullable<int> CalcularMulta { get; set; }
        public Nullable<decimal> Juros { get; set; }
        public Nullable<int> CalcularJuros { get; set; }
        public Nullable<decimal> CMonetaria { get; set; }
        public Nullable<int> CalcularCMonetaria { get; set; }
        public Nullable<decimal> Desconto { get; set; }
        public Nullable<int> CalcularDesconto { get; set; }
        public string Descricao { get; set; }
    
        public virtual Banco Banco1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caixinha> Caixinha { get; set; }
        public virtual Carteira Carteira1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoFiscal> DocumentoFiscal { get; set; }
        public virtual Empresa Empresa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recebimento> Recebimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaBancaria> TransferenciaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaBancaria> TransferenciaBancaria1 { get; set; }
    }
}
