//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpresaDocumento()
        {
            this.EmpresaDocumentoBlob = new HashSet<EmpresaDocumentoBlob>();
        }
    
        public int Id { get; set; }
        public int Empresa { get; set; }
        public int TipoDocumento { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual TipoDocumento TipoDocumento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaDocumentoBlob> EmpresaDocumentoBlob { get; set; }
    }
}
