//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.DocumentoFiscal = new HashSet<DocumentoFiscal>();
            this.EmpresaContaBancaria = new HashSet<EmpresaContaBancaria>();
            this.Pagamento = new HashSet<Pagamento>();
            this.Pessoa = new HashSet<Pessoa>();
            this.EmpresaDocumento = new HashSet<EmpresaDocumento>();
            this.FatServicosPmsp = new HashSet<FatServicosPmsp>();
            this.Projeto = new HashSet<Projeto>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public string Documento { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Numero { get; set; }
        public string Identidade { get; set; }
        public string Complemento { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string SerialCertificado { get; set; }
        public Nullable<decimal> PercCargaTributaria { get; set; }
        public Nullable<decimal> AliquotaIssForaMunicipio { get; set; }
        public string CodServicoPmsp { get; set; }
        public string SerieRps { get; set; }
        public string CcmPmsp { get; set; }
        public bool EmiteNF { get; set; }
        public bool OptanteSimplesNacional { get; set; }
        public Nullable<int> NumUltimaRps { get; set; }
        public string FonteCargaTributaria { get; set; }
        public string Contato { get; set; }
        public Nullable<System.DateTime> CertificadoVencimento { get; set; }
        public string CertificadoSenha { get; set; }
        public byte[] Certificado { get; set; }
        public Nullable<decimal> AliquotaCOFINS { get; set; }
        public Nullable<decimal> AliquotaCSLL { get; set; }
        public Nullable<decimal> AliquotaINSS { get; set; }
        public Nullable<decimal> AliquotaIR { get; set; }
        public Nullable<decimal> AliquotaPIS { get; set; }
        public bool FaturamentoDireto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoFiscal> DocumentoFiscal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaContaBancaria> EmpresaContaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpresaDocumento> EmpresaDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FatServicosPmsp> FatServicosPmsp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto> Projeto { get; set; }
    }
}
