//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipamento()
        {
            this.ContratoAmbienteEquipamento = new HashSet<ContratoAmbienteEquipamento>();
            this.OrdemServico = new HashSet<OrdemServico>();
            this.Peca = new HashSet<Peca>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Grupo { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> SubTipo { get; set; }
        public Nullable<int> Marca { get; set; }
        public Nullable<int> Unidade { get; set; }
        public Nullable<int> Tamanho { get; set; }
        public Nullable<int> Potencia { get; set; }
        public Nullable<int> Tensao { get; set; }
        public Nullable<int> Corrente { get; set; }
        public Nullable<bool> Validade { get; set; }
        public Nullable<int> Temperatura { get; set; }
        public Nullable<int> Vazao { get; set; }
        public Nullable<int> Pressao { get; set; }
        public Nullable<int> CadastradoPor { get; set; }
        public Nullable<System.DateTime> CadastradoEm { get; set; }
        public Nullable<int> TipoAmbiente { get; set; }
        public Nullable<bool> Fluido { get; set; }
        public Nullable<int> Refrigerante { get; set; }
    
        public virtual AmbienteTipo AmbienteTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoAmbienteEquipamento> ContratoAmbienteEquipamento { get; set; }
        public virtual EquipamentoCategoria EquipamentoCategoria { get; set; }
        public virtual EquipamentoCorrente EquipamentoCorrente { get; set; }
        public virtual EquipamentoGrupo EquipamentoGrupo { get; set; }
        public virtual EquipamentoMarca EquipamentoMarca { get; set; }
        public virtual EquipamentoPotencia EquipamentoPotencia { get; set; }
        public virtual EquipamentoPressao EquipamentoPressao { get; set; }
        public virtual EquipamentoRefrigerante EquipamentoRefrigerante { get; set; }
        public virtual EquipamentoSubTipo EquipamentoSubTipo { get; set; }
        public virtual EquipamentoTamanho EquipamentoTamanho { get; set; }
        public virtual EquipamentoTemperatura EquipamentoTemperatura { get; set; }
        public virtual EquipamentoTensao EquipamentoTensao { get; set; }
        public virtual EquipamentoTipo EquipamentoTipo { get; set; }
        public virtual EquipamentoUnidade EquipamentoUnidade { get; set; }
        public virtual EquipamentoVazao EquipamentoVazao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Peca> Peca { get; set; }
    }
}
