//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMEAAcaoCorretivaAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FMEAAcaoCorretivaAlbum()
        {
            this.FMEAAcaoCorretivaImagem = new HashSet<FMEAAcaoCorretivaImagem>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int AcaoCorretiva { get; set; }
        public string Conclusao { get; set; }
    
        public virtual FMEAAcaoCorretiva FMEAAcaoCorretiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FMEAAcaoCorretivaImagem> FMEAAcaoCorretivaImagem { get; set; }
    }
}
