//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMEA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FMEA()
        {
            this.FMEATipo = new HashSet<FMEATipo>();
            this.AmbienteTipo = new HashSet<AmbienteTipo>();
            this.EquipamentoGrupo = new HashSet<EquipamentoGrupo>();
            this.EquipamentoSubTipo = new HashSet<EquipamentoSubTipo>();
            this.EquipamentoTipo = new HashSet<EquipamentoTipo>();
            this.EspecialidadePreventiva = new HashSet<EspecialidadePreventiva>();
            this.FMEAModoFalha1 = new HashSet<FMEAModoFalha>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> ModoFalha { get; set; }
    
        public virtual FMEAModoFalha FMEAModoFalha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FMEATipo> FMEATipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AmbienteTipo> AmbienteTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipamentoGrupo> EquipamentoGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipamentoSubTipo> EquipamentoSubTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipamentoTipo> EquipamentoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialidadePreventiva> EspecialidadePreventiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FMEAModoFalha> FMEAModoFalha1 { get; set; }
    }
}
