//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMEAAcaoCorretivaVideo
    {
        public int Id { get; set; }
        public int AcaoCorretiva { get; set; }
        public string Descricao { get; set; }
        public string IdVideo { get; set; }
    
        public virtual FMEAAcaoCorretiva FMEAAcaoCorretiva { get; set; }
    }
}
