//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuncaoMLR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FuncaoMLR()
        {
            this.FuncaoMeta = new HashSet<FuncaoMeta>();
        }
    
        public int Id { get; set; }
        public int Funcao { get; set; }
        public string Descricao { get; set; }
        public bool IncidenciaBruto { get; set; }
        public Nullable<decimal> IncidenciaPercentual { get; set; }
        public Nullable<decimal> IncidenciaValor { get; set; }
        public bool SobreOs { get; set; }
        public bool SobreCentroLucro { get; set; }
        public bool SobreEmpresa { get; set; }
        public bool SobreCadastro { get; set; }
        public bool SobreVisita { get; set; }
        public bool SobreProspeccao { get; set; }
        public Nullable<int> CentroLucro { get; set; }
        public Nullable<bool> Bdi { get; set; }
        public Nullable<int> Periodicidade { get; set; }
    
        public virtual Funcao Funcao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncaoMeta> FuncaoMeta { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
