//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LancamentoPagar
    {
        public int Id { get; set; }
        public Nullable<int> OrdemServico { get; set; }
        public Nullable<int> Beneficiario { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public decimal Valor { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<int> OrcamentoTerceiro { get; set; }
        public Nullable<int> Projeto { get; set; }
        public bool Liberado { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual PagamentoCategoria PagamentoCategoria { get; set; }
        public virtual OrcamentoTerceiro OrcamentoTerceiro1 { get; set; }
        public virtual OrdemServico OrdemServico1 { get; set; }
        public virtual Projeto Projeto1 { get; set; }
    }
}
