//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcadorPesquisa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarcadorPesquisa()
        {
            this.PessoaContato = new HashSet<PessoaContato>();
            this.PessoaContatoMarcadorPesquisa = new HashSet<PessoaContatoMarcadorPesquisa>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string TagColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaContato> PessoaContato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaContatoMarcadorPesquisa> PessoaContatoMarcadorPesquisa { get; set; }
    }
}
