//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentoTerceiroServico
    {
        public int Id { get; set; }
        public int OrcamentoTerceiro { get; set; }
        public int Servico { get; set; }
    
        public virtual OrcamentoServico OrcamentoServico { get; set; }
        public virtual OrcamentoServico OrcamentoServico1 { get; set; }
        public virtual OrcamentoTerceiro OrcamentoTerceiro1 { get; set; }
    }
}
