//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentoMaterialServico
    {
        public int Id { get; set; }
        public int OrcamentoMaterial { get; set; }
        public int Servico { get; set; }
    
        public virtual OrcamentoMaterial OrcamentoMaterial1 { get; set; }
        public virtual OrcamentoServico OrcamentoServico { get; set; }
    }
}
