//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentoServico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrcamentoServico()
        {
            this.OrcamentoMaterialServico = new HashSet<OrcamentoMaterialServico>();
            this.OrcamentoTerceiroServico = new HashSet<OrcamentoTerceiroServico>();
            this.OrcamentoTerceiroServico1 = new HashSet<OrcamentoTerceiroServico>();
        }
    
        public int Id { get; set; }
        public string Categoria { get; set; }
        public decimal ValorMo { get; set; }
        public decimal ValorMoBdi { get; set; }
        public decimal ValorMa { get; set; }
        public decimal ValorMaBdi { get; set; }
        public decimal Quantidade { get; set; }
        public Nullable<int> Unidade { get; set; }
        public string Descricao { get; set; }
        public int Orcamento { get; set; }
        public int Posicao { get; set; }
    
        public virtual Orcamento Orcamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoMaterialServico> OrcamentoMaterialServico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoTerceiroServico> OrcamentoTerceiroServico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoTerceiroServico> OrcamentoTerceiroServico1 { get; set; }
        public virtual Unidade Unidade1 { get; set; }
    }
}
