//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentoMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrcamentoMaterial()
        {
            this.OrcamentoMaterialDocumento = new HashSet<OrcamentoMaterialDocumento>();
            this.OrcamentoMaterialServico = new HashSet<OrcamentoMaterialServico>();
        }
    
        public int Id { get; set; }
        public int Orcamento { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> Fornecedor { get; set; }
        public decimal Quantidade { get; set; }
        public decimal Valor { get; set; }
        public int Unidade { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> DataSolicitacao { get; set; }
        public string LocalEntrega { get; set; }
        public Nullable<System.DateTime> DataCompra { get; set; }
        public Nullable<decimal> ValorCompra { get; set; }
        public Nullable<bool> Comprado { get; set; }
        public Nullable<int> ChecklistPendencia { get; set; }
    
        public virtual ChecklistPendencia ChecklistPendencia1 { get; set; }
        public virtual Orcamento Orcamento1 { get; set; }
        public virtual TipoMaterial TipoMaterial { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Unidade Unidade1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoMaterialDocumento> OrcamentoMaterialDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoMaterialServico> OrcamentoMaterialServico { get; set; }
    }
}
