//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrcamentoMaterialDocumento
    {
        public int Id { get; set; }
        public int Material { get; set; }
        public string Nome { get; set; }
        public string Caminho { get; set; }
        public int EnviadoPor { get; set; }
        public System.DateTime EnviadoEm { get; set; }
        public string Observacao { get; set; }
    
        public virtual OrcamentoMaterial OrcamentoMaterial { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
