//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoHistoricoFollowUp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServicoHistoricoFollowUp()
        {
            this.OrdemServicoDocumentoFollowUp = new HashSet<OrdemServicoDocumentoFollowUp>();
        }
    
        public int Id { get; set; }
        public int OrdemServico { get; set; }
        public int Usuario { get; set; }
        public System.DateTime DataAcao { get; set; }
        public string Acao { get; set; }
        public string Observacao { get; set; }
        public string ProximaAcao { get; set; }
        public Nullable<System.DateTime> DataProximaAcao { get; set; }
    
        public virtual OrdemServico OrdemServico1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoDocumentoFollowUp> OrdemServicoDocumentoFollowUp { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
