//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoParcelamento
    {
        public int Id { get; set; }
        public int OrdemServico { get; set; }
        public decimal ValorBruto { get; set; }
        public string Observacao { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataSignificativa { get; set; }
    
        public virtual OrdemServico OrdemServico1 { get; set; }
    }
}
