//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoDocumentoFollowUp
    {
        public int Id { get; set; }
        public int Historico { get; set; }
        public string Caminho { get; set; }
    
        public virtual OrdemServicoHistoricoFollowUp OrdemServicoHistoricoFollowUp { get; set; }
    }
}
