//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoStatusHistorico
    {
        public int Id { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public int OrdemServico { get; set; }
        public int Pessoa { get; set; }
        public string Observacao { get; set; }
        public int De { get; set; }
        public int Para { get; set; }
    
        public virtual OrdemServico OrdemServico1 { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
    }
}
