//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServicoDocumento()
        {
            this.OrdemServico1 = new HashSet<OrdemServico>();
            this.OrdemServico3 = new HashSet<OrdemServico>();
        }
    
        public int Id { get; set; }
        public Nullable<int> OrdemServico { get; set; }
        public string Nome { get; set; }
        public string Caminho { get; set; }
        public int EnviadoPor { get; set; }
        public System.DateTime EnviadoEm { get; set; }
        public string Observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico1 { get; set; }
        public virtual OrdemServico OrdemServico2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico3 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
