//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoPesquisaSatisfacao
    {
        public int Id { get; set; }
        public int OrdemServico { get; set; }
        public System.DateTime DataPreenchimento { get; set; }
        public string ClassificacaoPostura { get; set; }
        public string ClassificacaoNossaEmpresa { get; set; }
        public string Observacao { get; set; }
        public int RecomendacaoParaAmigos { get; set; }
        public string LojaSite { get; set; }
        public string ClassificacaoQualidadeServico { get; set; }
        public string Pontualidade { get; set; }
        public string ClassificacaoSatisfacao { get; set; }
    
        public virtual OrdemServico OrdemServico1 { get; set; }
    }
}
