//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoChecklistAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServicoChecklistAlbum()
        {
            this.ChecklistPendencia = new HashSet<ChecklistPendencia>();
            this.OrdemServicoChecklistImagem = new HashSet<OrdemServicoChecklistImagem>();
        }
    
        public int Id { get; set; }
        public int OrdemServicoChecklist { get; set; }
        public string Descricao { get; set; }
        public string Conclusao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistPendencia> ChecklistPendencia { get; set; }
        public virtual OrdemServicoChecklist OrdemServicoChecklist1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoChecklistImagem> OrdemServicoChecklistImagem { get; set; }
    }
}
