//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoVisitaAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServicoVisitaAlbum()
        {
            this.OrdemServicoVisitaImagem = new HashSet<OrdemServicoVisitaImagem>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int Visita { get; set; }
        public string Conclusao { get; set; }
    
        public virtual OrdemServicoVisita OrdemServicoVisita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoVisitaImagem> OrdemServicoVisitaImagem { get; set; }
    }
}
