//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServico()
        {
            this.CaixinhaLancada = new HashSet<CaixinhaLancada>();
            this.ContasPagar = new HashSet<ContasPagar>();
            this.DocumentoFiscal = new HashSet<DocumentoFiscal>();
            this.LancamentoPagar = new HashSet<LancamentoPagar>();
            this.Orcamento = new HashSet<Orcamento>();
            this.OrdemServicoAlbum = new HashSet<OrdemServicoAlbum>();
            this.OrdemServicoComunicacao = new HashSet<OrdemServicoComunicacao>();
            this.OrdemServicoDocumento1 = new HashSet<OrdemServicoDocumento>();
            this.OrdemServicoParcelamento = new HashSet<OrdemServicoParcelamento>();
            this.OrdemServicoStatusHistorico = new HashSet<OrdemServicoStatusHistorico>();
            this.OrdemServicoHistorico = new HashSet<OrdemServicoHistorico>();
            this.OrdemServicoChecklist = new HashSet<OrdemServicoChecklist>();
            this.Pagamento = new HashSet<Pagamento>();
            this.Recebimento = new HashSet<Recebimento>();
            this.OrdemServicoAvaliacao = new HashSet<OrdemServicoAvaliacao>();
            this.OrdemServicoHistoricoFollowUp = new HashSet<OrdemServicoHistoricoFollowUp>();
            this.OrdemServicoPesquisa = new HashSet<OrdemServicoPesquisa>();
            this.OrdemServicoPesquisaSatisfacao = new HashSet<OrdemServicoPesquisaSatisfacao>();
            this.OrdemServicoVisita = new HashSet<OrdemServicoVisita>();
            this.Pessoa7 = new HashSet<Pessoa>();
            this.Pessoa8 = new HashSet<Pessoa>();
        }
    
        public int Id { get; set; }
        public int Cliente { get; set; }
        public string Ocorrencia { get; set; }
        public string Observacao { get; set; }
        public int Situacao { get; set; }
        public int Projeto { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataVisita { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> Revisao { get; set; }
        public Nullable<int> CadastradoPor { get; set; }
        public Nullable<System.DateTime> DataPrevisaoVisita { get; set; }
        public Nullable<System.DateTime> DataExecucaoInicioPrevisao { get; set; }
        public Nullable<System.DateTime> DataExecucaoFimPrevisao { get; set; }
        public Nullable<System.DateTime> DataExecucaoInicio { get; set; }
        public Nullable<System.DateTime> DataExecucaoFim { get; set; }
        public string CondicaoComercial { get; set; }
        public bool ComPendencia { get; set; }
        public Nullable<int> Especialidade { get; set; }
        public Nullable<int> Contrato { get; set; }
        public string OrdemCompra { get; set; }
        public string AprovadoEmail { get; set; }
        public Nullable<int> AprovadoDocumento { get; set; }
        public Nullable<int> OrdemCompraDocumento { get; set; }
        public Nullable<decimal> ValorAprovado { get; set; }
        public int StatusNegocio { get; set; }
        public Nullable<int> Motivo { get; set; }
        public Nullable<System.DateTime> DataEnvioProposta { get; set; }
        public Nullable<decimal> ValorDespesa { get; set; }
        public Nullable<int> Solicitante { get; set; }
        public Nullable<int> TipoEquipe { get; set; }
        public Nullable<System.DateTime> DataPrevisaoProposta { get; set; }
        public Nullable<bool> PrevisaoPropostaCliente { get; set; }
        public Nullable<System.DateTime> DataFollowUp { get; set; }
        public Nullable<int> FechadorNegocio { get; set; }
        public Nullable<int> Criticidade { get; set; }
        public string DescritivoNF { get; set; }
        public Nullable<System.TimeSpan> HoraFimPrevisaoVisita { get; set; }
        public Nullable<int> Supervisor { get; set; }
        public Nullable<int> HelpDesk { get; set; }
        public Nullable<int> TamanhoServico { get; set; }
        public Nullable<bool> PossuiContrato { get; set; }
        public Nullable<int> AcompComercial { get; set; }
        public Nullable<int> Ambiente { get; set; }
        public Nullable<int> Equipamento { get; set; }
        public Nullable<int> Orcamentista { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<System.DateTime> DataSignificativa { get; set; }
        public Nullable<System.DateTime> DataAprovacao { get; set; }
        public Nullable<System.TimeSpan> HoraPrevisaoChegada { get; set; }
        public Nullable<System.TimeSpan> HoraAcionamento { get; set; }
        public Nullable<int> Pendencias { get; set; }
    
        public virtual Ambiente Ambiente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaixinhaLancada> CaixinhaLancada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContasPagar> ContasPagar { get; set; }
        public virtual Contrato Contrato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoFiscal> DocumentoFiscal { get; set; }
        public virtual Equipamento Equipamento1 { get; set; }
        public virtual Especialidade Especialidade1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LancamentoPagar> LancamentoPagar { get; set; }
        public virtual MotivoPerdaOs MotivoPerdaOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orcamento> Orcamento { get; set; }
        public virtual Orcamento Orcamento1 { get; set; }
        public virtual OrdemServicoDocumento OrdemServicoDocumento { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Pessoa Pessoa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoAlbum> OrdemServicoAlbum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoComunicacao> OrdemServicoComunicacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoDocumento> OrdemServicoDocumento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoParcelamento> OrdemServicoParcelamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoStatusHistorico> OrdemServicoStatusHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoHistorico> OrdemServicoHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoChecklist> OrdemServicoChecklist { get; set; }
        public virtual OrdemServicoDocumento OrdemServicoDocumento2 { get; set; }
        public virtual Projeto Projeto1 { get; set; }
        public virtual Situacao Situacao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recebimento> Recebimento { get; set; }
        public virtual Pessoa Pessoa2 { get; set; }
        public virtual Pessoa Pessoa3 { get; set; }
        public virtual Pessoa Pessoa4 { get; set; }
        public virtual Pessoa Pessoa5 { get; set; }
        public virtual PessoaContato PessoaContato { get; set; }
        public virtual Pessoa Pessoa6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoAvaliacao> OrdemServicoAvaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoHistoricoFollowUp> OrdemServicoHistoricoFollowUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoPesquisa> OrdemServicoPesquisa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoPesquisaSatisfacao> OrdemServicoPesquisaSatisfacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoVisita> OrdemServicoVisita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa8 { get; set; }
    }
}
