//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServicoHistorico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdemServicoHistorico()
        {
            this.Pessoa1 = new HashSet<Pessoa>();
        }
    
        public int Id { get; set; }
        public int OrdemServico { get; set; }
        public int EditadoPor { get; set; }
        public System.DateTime EditadoEm { get; set; }
        public Nullable<System.DateTime> DataPrevisaoVisita { get; set; }
        public Nullable<System.DateTime> DataFollowUp { get; set; }
    
        public virtual OrdemServico OrdemServico1 { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa1 { get; set; }
    }
}
