//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagamentoBkp
    {
        public int Id { get; set; }
        public Nullable<int> Categoria { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<int> Beneficiario { get; set; }
        public string NotaFiscal { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> FaturadoPara { get; set; }
        public Nullable<int> Projeto { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> OrdemServico { get; set; }
        public Nullable<decimal> Encargos { get; set; }
        public Nullable<bool> Protesto { get; set; }
        public Nullable<bool> Provisionado { get; set; }
        public Nullable<int> Criticidade { get; set; }
        public Nullable<bool> Fixo { get; set; }
    }
}
