//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PesquisaSatisfacaoGestor
    {
        public int Id { get; set; }
        public System.DateTime DataPreenchimento { get; set; }
        public int ClassificacaoSatisfacao { get; set; }
        public string ClassificacaoSatisfacaoSugestaoMelhoria { get; set; }
        public string ClassificacaoRecomendacao { get; set; }
        public string ClassificacaoRecomendacaoSugestaoMelhoria { get; set; }
        public string ClassificacaoComunicacao { get; set; }
        public string ClassificacaoComunicacaoSugestaoMelhoria { get; set; }
        public string ClassificacaoAgilidade { get; set; }
        public string ClassificacaoAgilidadeSugestaoMelhoria { get; set; }
        public string ClassificacaoAtendimento { get; set; }
        public string ClassificacaoAtendimentoSugestaoMelhoria { get; set; }
        public string ComentarioSugestao { get; set; }
        public int PessoaContato { get; set; }
    
        public virtual PessoaContato PessoaContato1 { get; set; }
    }
}
