//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PessoaCaixinha
    {
        public int Beneficiario { get; set; }
        public Nullable<decimal> Deposito { get; set; }
        public Nullable<decimal> Lancado { get; set; }
        public Nullable<decimal> Saldo { get; set; }
    }
}
