//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.Caixinha = new HashSet<Caixinha>();
            this.CaixinhaLancada = new HashSet<CaixinhaLancada>();
            this.CaixinhaLancada1 = new HashSet<CaixinhaLancada>();
            this.CaixinhaLancada2 = new HashSet<CaixinhaLancada>();
            this.CaixinhaLancadaAprovacao = new HashSet<CaixinhaLancadaAprovacao>();
            this.ChecklistPendencia = new HashSet<ChecklistPendencia>();
            this.ContaBancaria = new HashSet<ContaBancaria>();
            this.ContasPagar = new HashSet<ContasPagar>();
            this.Contrato = new HashSet<Contrato>();
            this.Contrato1 = new HashSet<Contrato>();
            this.Contrato2 = new HashSet<Contrato>();
            this.Contrato3 = new HashSet<Contrato>();
            this.Contrato4 = new HashSet<Contrato>();
            this.ContratoEquipeEspecialidade = new HashSet<ContratoEquipeEspecialidade>();
            this.ContratoTerceiro = new HashSet<ContratoTerceiro>();
            this.ContratoTerceiroEspecialidade = new HashSet<ContratoTerceiroEspecialidade>();
            this.ControlePonto = new HashSet<ControlePonto>();
            this.DocumentoFiscal = new HashSet<DocumentoFiscal>();
            this.Equipamento = new HashSet<Equipamento>();
            this.LancamentoPagar1 = new HashSet<LancamentoPagar>();
            this.Notas = new HashSet<Notas>();
            this.Orcamento = new HashSet<Orcamento>();
            this.OrcamentoMaterial = new HashSet<OrcamentoMaterial>();
            this.OrcamentoMaterialDocumento = new HashSet<OrcamentoMaterialDocumento>();
            this.OrcamentoRecurso = new HashSet<OrcamentoRecurso>();
            this.OrcamentoTerceiro = new HashSet<OrcamentoTerceiro>();
            this.OrdemServico = new HashSet<OrdemServico>();
            this.OrdemServico1 = new HashSet<OrdemServico>();
            this.OrdemServico2 = new HashSet<OrdemServico>();
            this.OrdemServico3 = new HashSet<OrdemServico>();
            this.OrdemServico4 = new HashSet<OrdemServico>();
            this.OrdemServico5 = new HashSet<OrdemServico>();
            this.OrdemServico6 = new HashSet<OrdemServico>();
            this.OrdemServicoAvaliacao = new HashSet<OrdemServicoAvaliacao>();
            this.OrdemServicoChecklist = new HashSet<OrdemServicoChecklist>();
            this.OrdemServicoChecklist1 = new HashSet<OrdemServicoChecklist>();
            this.OrdemServicoChecklistHistorico = new HashSet<OrdemServicoChecklistHistorico>();
            this.OrdemServicoComunicacao = new HashSet<OrdemServicoComunicacao>();
            this.OrdemServicoDocumento = new HashSet<OrdemServicoDocumento>();
            this.OrdemServicoHistorico = new HashSet<OrdemServicoHistorico>();
            this.OrdemServicoHistoricoFollowUp = new HashSet<OrdemServicoHistoricoFollowUp>();
            this.OrdemServicoStatusHistorico = new HashSet<OrdemServicoStatusHistorico>();
            this.Pagamento = new HashSet<Pagamento>();
            this.Pagamento1 = new HashSet<Pagamento>();
            this.PagamentoComunicacao = new HashSet<PagamentoComunicacao>();
            this.PagamentoDocumento = new HashSet<PagamentoDocumento>();
            this.PagamentoHistorico = new HashSet<PagamentoHistorico>();
            this.PagamentoRecibo = new HashSet<PagamentoRecibo>();
            this.Pessoa1 = new HashSet<Pessoa>();
            this.Pessoa11 = new HashSet<Pessoa>();
            this.Pessoa12 = new HashSet<Pessoa>();
            this.Pessoa13 = new HashSet<Pessoa>();
            this.Pessoa14 = new HashSet<Pessoa>();
            this.Pessoa15 = new HashSet<Pessoa>();
            this.PessoaContaBancaria = new HashSet<PessoaContaBancaria>();
            this.PessoaContato = new HashSet<PessoaContato>();
            this.PessoaDocumento = new HashSet<PessoaDocumento>();
            this.RecebimentoHistorico = new HashSet<RecebimentoHistorico>();
            this.RecebimentoDocumento = new HashSet<RecebimentoDocumento>();
            this.Recebimento = new HashSet<Recebimento>();
            this.TransacaoBancaria = new HashSet<TransacaoBancaria>();
            this.PessoaImagem = new HashSet<PessoaImagem>();
            this.PontoFalta = new HashSet<PontoFalta>();
            this.PontoFerias = new HashSet<PontoFerias>();
            this.PontoPedidosHoraExtra = new HashSet<PontoPedidosHoraExtra>();
            this.PontoRegistro = new HashSet<PontoRegistro>();
            this.TarefaGrupos = new HashSet<TarefaGrupos>();
            this.TarefaListas = new HashSet<TarefaListas>();
            this.Tarefas = new HashSet<Tarefas>();
            this.Contrato5 = new HashSet<Contrato>();
            this.OrdemServicoHistorico1 = new HashSet<OrdemServicoHistorico>();
            this.OrdemServico7 = new HashSet<OrdemServico>();
            this.OrdemServico8 = new HashSet<OrdemServico>();
            this.Menu = new HashSet<Menu>();
            this.PagamentoCategoria = new HashSet<PagamentoCategoria>();
            this.Projeto = new HashSet<Projeto>();
            this.EspecialidadePreventiva = new HashSet<EspecialidadePreventiva>();
            this.Funcao2 = new HashSet<Funcao>();
            this.PersonaAlvo = new HashSet<PersonaAlvo>();
            this.TipoMaoObra = new HashSet<TipoMaoObra>();
            this.TipoMaterial = new HashSet<TipoMaterial>();
            this.Tarefas1 = new HashSet<Tarefas>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Nome { get; set; }
        public string Apelido { get; set; }
        public string Identidade { get; set; }
        public string Cep { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Observacao { get; set; }
        public string Documento { get; set; }
        public bool Funcionario { get; set; }
        public bool Cliente { get; set; }
        public bool Fornecedor { get; set; }
        public bool Terceiro { get; set; }
        public Nullable<int> Superior { get; set; }
        public string Senha { get; set; }
        public Nullable<int> CadastradoPor { get; set; }
        public Nullable<System.DateTime> CadastradoEm { get; set; }
        public Nullable<int> GerenteContas { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public bool Status { get; set; }
        public Nullable<int> EnquadramentoTributario { get; set; }
        public string NomeIndex { get; set; }
        public string EmailCorporativo { get; set; }
        public string TelefoneCorporativo { get; set; }
        public Nullable<bool> Lead { get; set; }
        public Nullable<int> Prospector { get; set; }
        public Nullable<int> GerenteComercial { get; set; }
        public Nullable<int> ParceiroComercial { get; set; }
        public Nullable<int> ComoConheceu { get; set; }
        public int Situacao { get; set; }
        public Nullable<int> JanelaEmissaoNotaDe { get; set; }
        public Nullable<int> JanelaEmissaoNotaAte { get; set; }
        public Nullable<int> NivelAcesso { get; set; }
        public Nullable<bool> RequerOrdemCompra { get; set; }
        public bool Operacional { get; set; }
        public bool Financeiro { get; set; }
        public bool Comercial { get; set; }
        public bool RecursosHumanos { get; set; }
        public bool Admin { get; set; }
        public bool AprovaCaixinha { get; set; }
        public Nullable<int> PerfilAcesso { get; set; }
        public Nullable<int> Departamento { get; set; }
        public bool Parceiro { get; set; }
        public Nullable<int> Funcao { get; set; }
        public Nullable<int> Probabilidade { get; set; }
        public Nullable<int> PrazoPagamento { get; set; }
        public byte VersaoSenha { get; set; }
        public string Lojas { get; set; }
        public Nullable<int> EmpresaFaturamento { get; set; }
        public Nullable<int> FormaPagamentoFaturamento { get; set; }
        public Nullable<int> ContaBancariaFaturamento { get; set; }
        public string TextoDiscriminacaoFaturamento { get; set; }
        public string CmPmsp { get; set; }
        public bool RequerDescritivoNF { get; set; }
        public Nullable<int> QtdFuncionarios { get; set; }
        public Nullable<int> QtdFiliais { get; set; }
        public Nullable<int> NivelInteresseCliente { get; set; }
        public Nullable<int> NivelInteresseEmpresa { get; set; }
        public Nullable<int> PontoJornadaId { get; set; }
        public Nullable<decimal> Score { get; set; }
        public bool LancamentoPagar { get; set; }
        public bool AprovaCaixinhaFinanceiro { get; set; }
        public bool ExcluiPgtoRecebimento { get; set; }
        public Nullable<int> LocalAcesso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caixinha> Caixinha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaixinhaLancada> CaixinhaLancada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaixinhaLancada> CaixinhaLancada1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaixinhaLancada> CaixinhaLancada2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaixinhaLancadaAprovacao> CaixinhaLancadaAprovacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChecklistPendencia> ChecklistPendencia { get; set; }
        public virtual ComoConheceu ComoConheceu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContaBancaria> ContaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContasPagar> ContasPagar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoEquipeEspecialidade> ContratoEquipeEspecialidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoTerceiro> ContratoTerceiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoTerceiroEspecialidade> ContratoTerceiroEspecialidade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlePonto> ControlePonto { get; set; }
        public virtual DepartamentoOrganizacao DepartamentoOrganizacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoFiscal> DocumentoFiscal { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EmpresaContaBancaria EmpresaContaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipamento> Equipamento { get; set; }
        public virtual Funcao Funcao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LancamentoPagar> LancamentoPagar1 { get; set; }
        public virtual NivelAcesso NivelAcesso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notas> Notas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orcamento> Orcamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoMaterial> OrcamentoMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoMaterialDocumento> OrcamentoMaterialDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoRecurso> OrcamentoRecurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrcamentoTerceiro> OrcamentoTerceiro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoAvaliacao> OrdemServicoAvaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoChecklist> OrdemServicoChecklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoChecklist> OrdemServicoChecklist1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoChecklistHistorico> OrdemServicoChecklistHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoComunicacao> OrdemServicoComunicacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoDocumento> OrdemServicoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoHistorico> OrdemServicoHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoHistoricoFollowUp> OrdemServicoHistoricoFollowUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoStatusHistorico> OrdemServicoStatusHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamento> Pagamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoComunicacao> PagamentoComunicacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoDocumento> PagamentoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoHistorico> PagamentoHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoRecibo> PagamentoRecibo { get; set; }
        public virtual PerfilAcesso PerfilAcesso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa1 { get; set; }
        public virtual Pessoa Pessoa2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa11 { get; set; }
        public virtual Pessoa Pessoa3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa12 { get; set; }
        public virtual Pessoa Pessoa4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa13 { get; set; }
        public virtual Pessoa Pessoa5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa14 { get; set; }
        public virtual Pessoa Pessoa6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa15 { get; set; }
        public virtual Pessoa Pessoa7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaContaBancaria> PessoaContaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaContato> PessoaContato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaDocumento> PessoaDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecebimentoHistorico> RecebimentoHistorico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecebimentoDocumento> RecebimentoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recebimento> Recebimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransacaoBancaria> TransacaoBancaria { get; set; }
        public virtual PontoJornada PontoJornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PessoaImagem> PessoaImagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PontoFalta> PontoFalta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PontoFerias> PontoFerias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PontoPedidosHoraExtra> PontoPedidosHoraExtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PontoRegistro> PontoRegistro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaGrupos> TarefaGrupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaListas> TarefaListas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarefas> Tarefas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServicoHistorico> OrdemServicoHistorico1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemServico> OrdemServico8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagamentoCategoria> PagamentoCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projeto> Projeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspecialidadePreventiva> EspecialidadePreventiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcao> Funcao2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaAlvo> PersonaAlvo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoMaoObra> TipoMaoObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TipoMaterial> TipoMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarefas> Tarefas1 { get; set; }
    }
}
