//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontoJornada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PontoJornada()
        {
            this.Funcao = new HashSet<Funcao>();
            this.Pessoa = new HashSet<Pessoa>();
        }
    
        public int Id { get; set; }
        public long HoraInicialPreIntervalo { get; set; }
        public long HoraFinalPreIntervalo { get; set; }
        public long HoraInicialPosIntervalo { get; set; }
        public long HoraFinalPosIntervalo { get; set; }
        public string Descricao { get; set; }
        public string DiaDaSemana { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcao> Funcao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa { get; set; }
    }
}
