//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontoRegistro
    {
        public int Id { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Accuracy { get; set; }
        public int TipoRegistroPonto { get; set; }
        public int SubTipoRegistroPonto { get; set; }
        public int PessoaId { get; set; }
        public string Descricao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
