//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PontoPedidosHoraExtra
    {
        public int Id { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public string Descricao { get; set; }
        public int Horas { get; set; }
        public int Minutos { get; set; }
        public System.DateTime Data { get; set; }
        public int Status { get; set; }
        public int PessoaId { get; set; }
        public Nullable<int> OrdemServicoId { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
