//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnSuiteBIEntities : DbContext
    {
        public OnSuiteBIEntities()
            : base("name=OnSuiteBIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AliquotaMunicipal> AliquotaMunicipal { get; set; }
        public virtual DbSet<Ambiente> Ambiente { get; set; }
        public virtual DbSet<AmbienteAndar> AmbienteAndar { get; set; }
        public virtual DbSet<AmbienteDescricao> AmbienteDescricao { get; set; }
        public virtual DbSet<AmbienteTipo> AmbienteTipo { get; set; }
        public virtual DbSet<AmbienteTorreBloco> AmbienteTorreBloco { get; set; }
        public virtual DbSet<ArquivoProcessamento> ArquivoProcessamento { get; set; }
        public virtual DbSet<Banco> Banco { get; set; }
        public virtual DbSet<Caixinha> Caixinha { get; set; }
        public virtual DbSet<CaixinhaCategoria> CaixinhaCategoria { get; set; }
        public virtual DbSet<CaixinhaLancada> CaixinhaLancada { get; set; }
        public virtual DbSet<CaixinhaLancadaAprovacao> CaixinhaLancadaAprovacao { get; set; }
        public virtual DbSet<Carteira> Carteira { get; set; }
        public virtual DbSet<ChecklistPendencia> ChecklistPendencia { get; set; }
        public virtual DbSet<ChecklistTemplate> ChecklistTemplate { get; set; }
        public virtual DbSet<ComoConheceu> ComoConheceu { get; set; }
        public virtual DbSet<Configuracoes> Configuracoes { get; set; }
        public virtual DbSet<ContaBancaria> ContaBancaria { get; set; }
        public virtual DbSet<ContasPagar> ContasPagar { get; set; }
        public virtual DbSet<ContasPagarRateio> ContasPagarRateio { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<ContratoAmbiente> ContratoAmbiente { get; set; }
        public virtual DbSet<ContratoAmbienteAlbum> ContratoAmbienteAlbum { get; set; }
        public virtual DbSet<ContratoAmbienteEquipamento> ContratoAmbienteEquipamento { get; set; }
        public virtual DbSet<ContratoAmbienteEquipamentoAlbum> ContratoAmbienteEquipamentoAlbum { get; set; }
        public virtual DbSet<ContratoAmbienteEquipamentoImagem> ContratoAmbienteEquipamentoImagem { get; set; }
        public virtual DbSet<ContratoAmbienteImagem> ContratoAmbienteImagem { get; set; }
        public virtual DbSet<ContratoAreaManutencao> ContratoAreaManutencao { get; set; }
        public virtual DbSet<ContratoDocumento> ContratoDocumento { get; set; }
        public virtual DbSet<ContratoDocumentoBlob> ContratoDocumentoBlob { get; set; }
        public virtual DbSet<ContratoEquipeEspecialidade> ContratoEquipeEspecialidade { get; set; }
        public virtual DbSet<ContratoTerceiro> ContratoTerceiro { get; set; }
        public virtual DbSet<ContratoTerceiroEspecialidade> ContratoTerceiroEspecialidade { get; set; }
        public virtual DbSet<ControlePonto> ControlePonto { get; set; }
        public virtual DbSet<DepartamentoOrganizacao> DepartamentoOrganizacao { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DocumentoFiscal> DocumentoFiscal { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EmpresaContaBancaria> EmpresaContaBancaria { get; set; }
        public virtual DbSet<EmpresaDocumento> EmpresaDocumento { get; set; }
        public virtual DbSet<EmpresaDocumentoBlob> EmpresaDocumentoBlob { get; set; }
        public virtual DbSet<Equipamento> Equipamento { get; set; }
        public virtual DbSet<EquipamentoCategoria> EquipamentoCategoria { get; set; }
        public virtual DbSet<EquipamentoCorrente> EquipamentoCorrente { get; set; }
        public virtual DbSet<EquipamentoGrupo> EquipamentoGrupo { get; set; }
        public virtual DbSet<EquipamentoMarca> EquipamentoMarca { get; set; }
        public virtual DbSet<EquipamentoModelo> EquipamentoModelo { get; set; }
        public virtual DbSet<EquipamentoPotencia> EquipamentoPotencia { get; set; }
        public virtual DbSet<EquipamentoPressao> EquipamentoPressao { get; set; }
        public virtual DbSet<EquipamentoRefrigerante> EquipamentoRefrigerante { get; set; }
        public virtual DbSet<EquipamentoSubTipo> EquipamentoSubTipo { get; set; }
        public virtual DbSet<EquipamentoTamanho> EquipamentoTamanho { get; set; }
        public virtual DbSet<EquipamentoTemperatura> EquipamentoTemperatura { get; set; }
        public virtual DbSet<EquipamentoTensao> EquipamentoTensao { get; set; }
        public virtual DbSet<EquipamentoTipo> EquipamentoTipo { get; set; }
        public virtual DbSet<EquipamentoUnidade> EquipamentoUnidade { get; set; }
        public virtual DbSet<EquipamentoVazao> EquipamentoVazao { get; set; }
        public virtual DbSet<Especialidade> Especialidade { get; set; }
        public virtual DbSet<EspecialidadePreventiva> EspecialidadePreventiva { get; set; }
        public virtual DbSet<FatServicosPmsp> FatServicosPmsp { get; set; }
        public virtual DbSet<FMEA> FMEA { get; set; }
        public virtual DbSet<FMEAAcaoCorretiva> FMEAAcaoCorretiva { get; set; }
        public virtual DbSet<FMEAAcaoCorretivaAlbum> FMEAAcaoCorretivaAlbum { get; set; }
        public virtual DbSet<FMEAAcaoCorretivaImagem> FMEAAcaoCorretivaImagem { get; set; }
        public virtual DbSet<FMEAAcaoCorretivaVideo> FMEAAcaoCorretivaVideo { get; set; }
        public virtual DbSet<FMEAEfeitoPotencial> FMEAEfeitoPotencial { get; set; }
        public virtual DbSet<FMEAModoFalha> FMEAModoFalha { get; set; }
        public virtual DbSet<FMEATipo> FMEATipo { get; set; }
        public virtual DbSet<Funcao> Funcao { get; set; }
        public virtual DbSet<FuncaoMeta> FuncaoMeta { get; set; }
        public virtual DbSet<FuncaoMLR> FuncaoMLR { get; set; }
        public virtual DbSet<ImagemGoogle> ImagemGoogle { get; set; }
        public virtual DbSet<LancamentoPagar> LancamentoPagar { get; set; }
        public virtual DbSet<Lembrete> Lembrete { get; set; }
        public virtual DbSet<MarcadorContato> MarcadorContato { get; set; }
        public virtual DbSet<MarcadorPesquisa> MarcadorPesquisa { get; set; }
        public virtual DbSet<MeioComunicacao> MeioComunicacao { get; set; }
        public virtual DbSet<MeioPagamento> MeioPagamento { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<ModeloLPU> ModeloLPU { get; set; }
        public virtual DbSet<ModeloLPUItem> ModeloLPUItem { get; set; }
        public virtual DbSet<MotivoPerdaOs> MotivoPerdaOs { get; set; }
        public virtual DbSet<MunicipioIbge> MunicipioIbge { get; set; }
        public virtual DbSet<NivelAcesso> NivelAcesso { get; set; }
        public virtual DbSet<NivelAcessoItem> NivelAcessoItem { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<Orcamento> Orcamento { get; set; }
        public virtual DbSet<OrcamentoAlbum> OrcamentoAlbum { get; set; }
        public virtual DbSet<OrcamentoImagem> OrcamentoImagem { get; set; }
        public virtual DbSet<OrcamentoMaterial> OrcamentoMaterial { get; set; }
        public virtual DbSet<OrcamentoMaterialDocumento> OrcamentoMaterialDocumento { get; set; }
        public virtual DbSet<OrcamentoMaterialServico> OrcamentoMaterialServico { get; set; }
        public virtual DbSet<OrcamentoRecurso> OrcamentoRecurso { get; set; }
        public virtual DbSet<OrcamentoServico> OrcamentoServico { get; set; }
        public virtual DbSet<OrcamentoTerceiro> OrcamentoTerceiro { get; set; }
        public virtual DbSet<OrcamentoTerceiroServico> OrcamentoTerceiroServico { get; set; }
        public virtual DbSet<OrdemServico> OrdemServico { get; set; }
        public virtual DbSet<OrdemServicoAlbum> OrdemServicoAlbum { get; set; }
        public virtual DbSet<OrdemServicoAvaliacao> OrdemServicoAvaliacao { get; set; }
        public virtual DbSet<OrdemServicoChecklist> OrdemServicoChecklist { get; set; }
        public virtual DbSet<OrdemServicoChecklistAlbum> OrdemServicoChecklistAlbum { get; set; }
        public virtual DbSet<OrdemServicoChecklistHistorico> OrdemServicoChecklistHistorico { get; set; }
        public virtual DbSet<OrdemServicoChecklistImagem> OrdemServicoChecklistImagem { get; set; }
        public virtual DbSet<OrdemServicoComunicacao> OrdemServicoComunicacao { get; set; }
        public virtual DbSet<OrdemServicoDocumento> OrdemServicoDocumento { get; set; }
        public virtual DbSet<OrdemServicoDocumentoFollowUp> OrdemServicoDocumentoFollowUp { get; set; }
        public virtual DbSet<OrdemServicoHistorico> OrdemServicoHistorico { get; set; }
        public virtual DbSet<OrdemServicoHistoricoFollowUp> OrdemServicoHistoricoFollowUp { get; set; }
        public virtual DbSet<OrdemServicoImagem> OrdemServicoImagem { get; set; }
        public virtual DbSet<OrdemServicoParcelamento> OrdemServicoParcelamento { get; set; }
        public virtual DbSet<OrdemServicoPesquisa> OrdemServicoPesquisa { get; set; }
        public virtual DbSet<OrdemServicoPesquisaSatisfacao> OrdemServicoPesquisaSatisfacao { get; set; }
        public virtual DbSet<OrdemServicoStatusHistorico> OrdemServicoStatusHistorico { get; set; }
        public virtual DbSet<OrdemServicoVisita> OrdemServicoVisita { get; set; }
        public virtual DbSet<OrdemServicoVisitaAlbum> OrdemServicoVisitaAlbum { get; set; }
        public virtual DbSet<OrdemServicoVisitaImagem> OrdemServicoVisitaImagem { get; set; }
        public virtual DbSet<OrdemServicoVisitaItem> OrdemServicoVisitaItem { get; set; }
        public virtual DbSet<Pagamento> Pagamento { get; set; }
        public virtual DbSet<PagamentoBkp> PagamentoBkp { get; set; }
        public virtual DbSet<PagamentoCategoria> PagamentoCategoria { get; set; }
        public virtual DbSet<PagamentoComunicacao> PagamentoComunicacao { get; set; }
        public virtual DbSet<PagamentoDocumento> PagamentoDocumento { get; set; }
        public virtual DbSet<PagamentoHistorico> PagamentoHistorico { get; set; }
        public virtual DbSet<PagamentoRateio> PagamentoRateio { get; set; }
        public virtual DbSet<PagamentoRecibo> PagamentoRecibo { get; set; }
        public virtual DbSet<Parcelamento> Parcelamento { get; set; }
        public virtual DbSet<Peca> Peca { get; set; }
        public virtual DbSet<PerfilAcesso> PerfilAcesso { get; set; }
        public virtual DbSet<PersonaAlvo> PersonaAlvo { get; set; }
        public virtual DbSet<PesquisaSatisfacaoGestor> PesquisaSatisfacaoGestor { get; set; }
        public virtual DbSet<PesquisaSatisfacaoGestorJornada> PesquisaSatisfacaoGestorJornada { get; set; }
        public virtual DbSet<PesquisaSatisfacaoGestorLog> PesquisaSatisfacaoGestorLog { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<PessoaContaBancaria> PessoaContaBancaria { get; set; }
        public virtual DbSet<PessoaContato> PessoaContato { get; set; }
        public virtual DbSet<PessoaContatoMarcadorPesquisa> PessoaContatoMarcadorPesquisa { get; set; }
        public virtual DbSet<PessoaDocumento> PessoaDocumento { get; set; }
        public virtual DbSet<PessoaDocumentoBlob> PessoaDocumentoBlob { get; set; }
        public virtual DbSet<PessoaImagem> PessoaImagem { get; set; }
        public virtual DbSet<PontoFalta> PontoFalta { get; set; }
        public virtual DbSet<PontoFeriadosRecessos> PontoFeriadosRecessos { get; set; }
        public virtual DbSet<PontoFerias> PontoFerias { get; set; }
        public virtual DbSet<PontoJornada> PontoJornada { get; set; }
        public virtual DbSet<PontoPedidosHoraExtra> PontoPedidosHoraExtra { get; set; }
        public virtual DbSet<PontoRegistro> PontoRegistro { get; set; }
        public virtual DbSet<Projeto> Projeto { get; set; }
        public virtual DbSet<Recebimento> Recebimento { get; set; }
        public virtual DbSet<RecebimentoDocumento> RecebimentoDocumento { get; set; }
        public virtual DbSet<RecebimentoHistorico> RecebimentoHistorico { get; set; }
        public virtual DbSet<Recorrencia> Recorrencia { get; set; }
        public virtual DbSet<Servico> Servico { get; set; }
        public virtual DbSet<ServicoCategoria> ServicoCategoria { get; set; }
        public virtual DbSet<ServicoSubTipo> ServicoSubTipo { get; set; }
        public virtual DbSet<ServicoTipo> ServicoTipo { get; set; }
        public virtual DbSet<Situacao> Situacao { get; set; }
        public virtual DbSet<Speech> Speech { get; set; }
        public virtual DbSet<TarefaGrupos> TarefaGrupos { get; set; }
        public virtual DbSet<TarefaListas> TarefaListas { get; set; }
        public virtual DbSet<Tarefas> Tarefas { get; set; }
        public virtual DbSet<TemplateDocTecnico> TemplateDocTecnico { get; set; }
        public virtual DbSet<TemplateProposta> TemplateProposta { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoMaoObra> TipoMaoObra { get; set; }
        public virtual DbSet<TipoMaterial> TipoMaterial { get; set; }
        public virtual DbSet<TipoProduto> TipoProduto { get; set; }
        public virtual DbSet<TransacaoBancaria> TransacaoBancaria { get; set; }
        public virtual DbSet<TransferenciaBancaria> TransferenciaBancaria { get; set; }
        public virtual DbSet<Unidade> Unidade { get; set; }
        public virtual DbSet<CentroCustoReduzido> CentroCustoReduzido { get; set; }
        public virtual DbSet<PessoaCaixinha> PessoaCaixinha { get; set; }
        public virtual DbSet<vwCentroCustoAgrupado> vwCentroCustoAgrupado { get; set; }
        public virtual DbSet<vwContasAPagar> vwContasAPagar { get; set; }
        public virtual DbSet<vwContasAReceber> vwContasAReceber { get; set; }
        public virtual DbSet<vwLancamentosAPagar> vwLancamentosAPagar { get; set; }
        public virtual DbSet<vwOrdemServico> vwOrdemServico { get; set; }
        public virtual DbSet<vwParcelamento> vwParcelamento { get; set; }
    }
}
