//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarefas()
        {
            this.TarefaListas = new HashSet<TarefaListas>();
            this.Pessoa1 = new HashSet<Pessoa>();
        }
    
        public int Id { get; set; }
        public int CriadorId { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> PrazoInicio { get; set; }
        public Nullable<System.DateTime> PrazoFim { get; set; }
        public Nullable<System.DateTime> ExecInicio { get; set; }
        public Nullable<System.DateTime> ExecFim { get; set; }
        public string ExecLink { get; set; }
        public int Status { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaListas> TarefaListas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pessoa> Pessoa1 { get; set; }
    }
}
