//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferenciaBancaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferenciaBancaria()
        {
            this.TransferenciaBancaria1 = new HashSet<TransferenciaBancaria>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public decimal Valor { get; set; }
        public int De { get; set; }
        public int Para { get; set; }
        public Nullable<int> TransferenciaOposta { get; set; }
    
        public virtual EmpresaContaBancaria EmpresaContaBancaria { get; set; }
        public virtual EmpresaContaBancaria EmpresaContaBancaria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferenciaBancaria> TransferenciaBancaria1 { get; set; }
        public virtual TransferenciaBancaria TransferenciaBancaria2 { get; set; }
    }
}
