//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwContasAReceber
    {
        public string Centro_de_Lucro { get; set; }
        public Nullable<int> Ordem_de_Servico { get; set; }
        public string Sacado { get; set; }
        public string Nota_Fiscal { get; set; }
        public System.DateTime Data_de_Emissao { get; set; }
        public System.DateTime Data_de_Vencimento { get; set; }
        public Nullable<System.DateTime> Data_de_Recebimento { get; set; }
        public decimal Valor_Bruto { get; set; }
        public decimal Valor_Liquido { get; set; }
        public Nullable<decimal> Aliquota { get; set; }
        public string Observacao { get; set; }
        public string Recebido_ { get; set; }
        public string Ocorrencia { get; set; }
        public string Ordem_de_Compra { get; set; }
        public string Tipo_OS { get; set; }
        public Nullable<int> Probabilidade { get; set; }
        public string Especialidade { get; set; }
        public string Tipo_Equipe { get; set; }
    }
}
