//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLancamentosAPagar
    {
        public Nullable<int> Ordem_de_Servico { get; set; }
        public string Centro_de_Custos { get; set; }
        public string Beneficiario { get; set; }
        public string Centro_de_Lucro { get; set; }
        public Nullable<System.DateTime> Data_de_Vencimento { get; set; }
        public Nullable<System.DateTime> Data_de_Emissao { get; set; }
        public decimal Valor { get; set; }
        public string Tipo_OS { get; set; }
        public string Situacao { get; set; }
        public Nullable<System.DateTime> Data_Execucao_Fim { get; set; }
        public string Tipo_Equipe { get; set; }
    }
}
