//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOperacional
    {
        public int Id { get; set; }
        public string UF { get; set; }
        public string Cidade { get; set; }
        public Nullable<int> Especialidade { get; set; }
        public string EspecialidadeDescricao { get; set; }
        public int Situacao { get; set; }
        public string SituacaoDescricao { get; set; }
        public int Tipo { get; set; }
        public string TipoDescricao { get; set; }
    }
}
