//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwParcelamento
    {
        public int Ordem_de_Servico { get; set; }
        public string Centro_de_Lucro { get; set; }
        public string Cliente { get; set; }
        public string Ordem_de_Compra { get; set; }
        public Nullable<System.DateTime> Data_de_Execucao { get; set; }
        public decimal Valor_Bruto { get; set; }
        public string Ocorrencia { get; set; }
        public string Observacao { get; set; }
        public string Especialidade { get; set; }
        public string Data_de_Envio { get; set; }
        public Nullable<System.DateTime> Data_de_Vencimento { get; set; }
        public Nullable<int> Probabilidade { get; set; }
        public string Tipo_Equipe { get; set; }
    }
}
